# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Giampaolo44
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Giampaolo44's blog.
  Attempts to master Markdown, Jekyll and the like, in order to build a blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://giampaolo44.com" # the base hostname & protocol for your site
twitter_username: giampaolo44
github_username:  giampaolo44
facebook_username: giampaolo.ferradini
linkedin_username: giampaoloferradini

# Build settings
markdown: kramdown
